### ISSUE TITLE
出现了错误，貌似不行了

### ISSUE THREAD

**Issue by hao203** [Rhilip/NSFC_conclusion_downloader#1]
`C:\Users\Administrator\NSFC_conclusion_downloader>python3 nsfc_downloader.py --ratify '81360540'
开始获取项目信息，项目编号： '81360540'
Traceback (most recent call last):
  File "nsfc_downloader.py", line 96, in <module>
    downloader.download(args.ratify)
  File "nsfc_downloader.py", line 40, in download
    r.raise_for_status()
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://output.nsfc.gov.cn/baseQuery/data/conclusionProjectInfo/'81360540'`

**Comment by Rhilip** [comment]
感觉是他们服务器临时性出问题，重新试试
